### PR TITLE
`always_run` is deprecated

### PR DESCRIPTION
**Pull request by carlalexander**
Replaced with new `check_mode` variable.

### CODE REVIEW

**Review by drybjed — APPROVED** [review]

**Comment by ypid** [comment]
@carlalexander What about `min_ansible_version: '2.0.0'` in [meta/main.yml](https://github.com/debops/ansible-php/blob/master/meta/main.yml)? Ref: https://github.com/debops/ansible-owncloud/issues/77#issuecomment-273407319

**Comment by carlalexander** [comment]
I honestly didn't think it would break outside `2.0.0`. I'd revert the change.

**Comment by ypid** [comment]
You are right. That is a bit unfortunate but at least the docs are clear about it: [Enabling or disabling check mode for tasks](https://docs.ansible.com/ansible/playbooks_checkmode.html#enabling-or-disabling-check-mode-for-tasks) :wink:

**Comment by muelli** [comment]
hrm. If check_mode is used, then ansible 2.2 needs to be used. IOW: It's not compatible with Ansible 2.0. So either this change needs to be reverted or meta/main.yml needs to list 2.2 as requirement. That would, however, break the currently stable Ubuntu as it ships 2.0.0.2.

When will ansible pull the always_run flag?

**Comment by ypid** [comment]
@muelli Hi, I have just been looking into this because it was still unfixed.

About Ansible 2.0.0.2 and Ubuntu. I just checked and it seems that Ubuntu does not have real security support for Ansible as you can see.

Ref: http://packages.ubuntu.com/search?suite=zesty&searchon=names&keywords=ansible

AFAIK the only supported Ansible versions are 2.1 and 2.2. All previous versions must be expected to have known security vulnerability and must not be used anymore. Please install Ansible manually on Ubuntu. Debian handles this much better as I expected it :wink:

Because of this DebOps will not support Ansible 2.0. Ansible 2.1 support should be retained as discussed.

**Comment by muelli** [comment]
fair enough. I guess meta/main.yml still needs to be updated then :)

**Comment by ypid** [comment]
I think the policy that DebOps only supports Ansible versions which are also supported has not been specified yet in the docs. Also, this is not automated yet to update each and every role in DebOps as soon as Ansible versions drop out of support.

Ref: https://github.com/ypid/ypid-ansible-common/blob/master/bin/ansible-update-min-version
Ref: https://github.com/ansible/ansible/issues/18375

**Pull request merged**
